### YamlMime:FAQ
metadata:
  title: Application and service availability issues FAQ
  description: This article lists the frequently asked questions about application and service availability for Microsoft Azure Cloud Services.
  ms.topic: faq
  ms.service: cloud-services
  ms.date: 07/23/2024
  author: hirenshah1
  ms.author: hirshah
  ms.reviewer: mimckitt
  ms.custom: compute-evergreen
title: 'Application and service availability issues for Azure Cloud Services (classic): Frequently asked questions (FAQs)'
summary: |
  [!INCLUDE [Cloud Services (classic) deprecation announcement](includes/deprecation-announcement.md)]
  
  This article includes frequently asked questions about application and service availability issues for [Microsoft Azure Cloud Services](https://azure.microsoft.com/services/cloud-services). You can also consult the [Cloud Services Virtual Machine (VM) Size page](cloud-services-sizes-specs.md) for size information.
  
  [!INCLUDE [support-disclaimer](~/reusable-content/ce-skilling/azure/includes/support-disclaimer.md)]
  

sections:
  - name: Ignored
    questions:
      - question: |
          My role got recycled. Was there any update rolled out for my cloud service?
        answer: |
          Roughly once a month, Microsoft releases a new Guest OS version for Microsoft Azure PaaS VMs.â€¯The Guest OS is only one such update in the pipeline. Many other factors can affect a release. In addition, Azure runs on hundreds of thousands of machines. Therefore, it's impossible to predict the exact date and time when your roles reboot. We update the Guest OS Update RSS Feed with the latest information that we have, but you should consider that reported time to be an approximate value. We're working on a plan to limit or precisely time reboots.
          
          For complete details about recent Guest OS updates, see [Azure Guest OS releases and SDK compatibility matrix](cloud-services-guestos-update-matrix.md).
          
          For helpful information on restarts and pointers to technical details of Guest and Host OS updates, see the Microsoft Developer Network (MSDN) blog post [Role Instance Restarts Due to OS Upgrades](/archive/blogs/kwill/role-instance-restarts-due-to-os-upgrades).
          
      - question: |
          Why does the first request to my cloud service take longer than usual after the service idles for some time?
        answer: |
          When the Web Server receives the first request, it first recompiles the code and then processes the request, which is why the first request takes longer than the others. By default, the app pool gets shut-down in cases of user inactivity. The app pool also recycles by default every 1,740 minutes (29 hours).
          
          Internet Information Services (IIS) application pools can be periodically recycled to avoid unstable states that can lead to application crashes, hangs, or memory leaks.
          
          The following documents help you understand and mitigate this issue:
          * [Fixing slow initial load for IIS](https://stackoverflow.com/questions/13386471/fixing-slow-initial-load-for-iis)
          * [IIS 7.5 web application first request after app-pool recycle slow](https://stackoverflow.com/questions/13917205/iis-7-5-web-application-first-request-after-app-pool-recycle-very-slow)
          
          If you want to change the default behavior of IIS, you need to use startup tasks. If you manually apply changes to the Web Role instances, the changes are eventually lost.
          
          For more information, see [How to configure and run startup tasks for a cloud service](cloud-services-startup-tasks.md).
