- name: Docker documentation
  href: index.yml
- name: Quickstart
  items:
  - name: Deploy an Ubuntu VM with Docker
    href: https://azure.microsoft.com/resources/templates/docker-simple-on-ubuntu/
  expanded: true
- name: Tutorials
  items:
  - name: Python Web App with Docker and PostgreSQL
    href: ../app-service/tutorial-python-postgresql-app.md?toc=%2fazure%2fpostgresql%2ftoc.json
  - name: CI/CD with Docker, Jenkins, and Linux
    href: /azure/developer/jenkins/pipeline-with-github-and-docker
- name: How-to guides
  items:
  - name: Docker VM extension
    href: https://github.com/Azure/azure-docker-extension/blob/master/README.md
  - name: Docker container registry
    href: ../container-registry/container-registry-get-started-portal.md
- name: Resources
  items:
  - name: Azure Roadmap
    href: https://azure.microsoft.com/roadmap/
  - name: Docker Azure driver
    href: https://docs.docker.com/machine/drivers/azure/
  - name: Docker Azure Site
    href: https://docs.docker.com/cloud/aci-integration/
  - name: Docker Site
    href: https://docker.com
