### YamlMime:YamlDocument
documentType: LandingData
title: Ansible on Azure Documentation
metadata:
  title: Ansible on Azure Documentation - Tutorials, samples, reference, and resources
  meta.description: Learn how to use Ansible to automate cloud provisioning, configuration management, and application deployments.
  services: terraform
  author: tomarcher
  manager: routlaw
  ms.service: ansible
  ms.tgt_pltfrm: na
  ms.devlang: devops
  ms.topic: landing-page
  ms.date: 01/11/2018
  ms.author: tarcher
abstract:
  description: Use Ansible to automate cloud provisioning, configuration management, and application deployments.
sections:
sections:
- title: 5-Minute Quickstarts
  items: 
  - type: paragraph
    text: Configure Ansible, and use it to create a Linux VM in Azure.
  - type: list
    style: icon48
    items: 
    - image: 
        src: /azure/media/index/azure_dev-9.svg
      text: Configure Ansible
      href: /azure/virtual-machines/linux/ansible-install-configure
    - image: 
        src: /azure/media/index/VirtualMachine.svg
      text: Create a Linux VM
      href: /azure/virtual-machines/linux/ansible-create-vm
- title: Step-by-Step Tutorials
  items:
  - type: paragraph
    text: Learn how to use Ansible to create and manage Azure compute and networking infrastructure.
  - type: list
    style: unordered
    items:
    - html: <a href="/azure/virtual-machines/linux/ansible-create-complete-vm">Create a complete Linux VM with Ansible</a>.
    - html: <a href="./ansible-run-playbook-in-cloudshell">Use Ansible in the Azure Cloud Shell</a>.
    - html: <a href="./ansible-manage-azure-dynamic-inventories">Manage your Azure dynamic inventories</a>.
- title: Samples
  items:
  - type: list
    style: unordered
    items:
    - html: <a href="https://github.com/Azure-Samples/ansible-playbooks">GitHub repository containing samples and best practices for building Ansible Playbooks for Azure</a>.
    - html: <a href="https://galaxy.ansible.com">Ansible Galaxy for creating, managing, and installing roles published by the community.</a>.
- title: Reference
  items:
  - type: list
    style: cards
    className: cardsD
    items:
    - title: Ansible modules for Azure
      html: <p><a href="http://docs.ansible.com/ansible/latest/azure_rm_acs_module.html">Manage Azure Container Service Instances</a></p><p><a href="http://docs.ansible.com/ansible/latest/azure_rm_functionapp_module.html">Manage Azure Functions</a></p><p><a href="http://docs.ansible.com/ansible/latest/azure_rm_loadbalancer_module.html">Manage Azure load balancers</a></p><p><a href="http://docs.ansible.com/ansible/latest/azure_rm_storageaccount_module.html"></a></p><p><a href="Manage Azure storage accounts"></a></p><p><a href="http://docs.ansible.com/ansible/latest/azure_rm_virtualmachine_module.html">Manage Azure virtual machines</a></p><p><a href="http://docs.ansible.com/ansible/latest/list_of_cloud_modules.html#azure">See all Ansible modules for Azure</a></p>
    - title: Ansible playbook roles for Azure
      html: <p><a href="https://galaxy.ansible.com/Azure/azure_modules/">azure_module</a></p><p><a href="https://galaxy.ansible.com/Azure/azure_preview_modules/">azure_preview_module</a></p>
    - title: Releases and features
      html: <p><a href="https://github.com/ansible/ansible/releases">Official releases</a></p><p><a href="./ansible-matrix.md">Features matrix for modules and roles</a></p>      