- name: Ansible on Azure
  href: ./index.yml
- name: Overview
  items:
  - name: About Ansible on Azure
    href: ./ansible-overview.md
- name: Quickstarts
  expanded: true
  items:
    - name: Install and configure Ansible
      href: /azure/virtual-machines/linux/ansible-install-configure
      maintainContext: true
    - name: Create a Linux VM
      href: /azure/virtual-machines/linux/ansible-create-vm
      maintainContext: true
- name: Tutorials 
  items:
  - name: Create complete Linux VM
    href: /azure/virtual-machines/linux/ansible-create-complete-vm
    maintainContext: true
  - name: Run a playbook in Cloud Shell
    href: ./ansible-run-playbook-in-cloudshell.md
    maintainContext: true
  - name: Manage your Azure dynamic inventories
    href: ./ansible-manage-azure-dynamic-inventories.md
    maintainContext: true
- name: Samples
  items:
  - name: Ansible playbooks for Azure
    href: https://github.com/Azure-Samples/ansible-playbooks
  - name: Ansible Galaxy
    href: https://galaxy.ansible.com
- name: Reference 
  items:
  - name: Modules for Azure
    items:
    - name: Ansible modules for Azure
      href: http://docs.ansible.com/ansible/latest/list_of_cloud_modules.html#azure
    - name: Ansible reference
      href: http://docs.ansible.com/ansible/latest/dev_guide/index.html
    - name: Ansible modules and features matrix
      href: ./ansible-matrix.md
  - name: Playbook roles for Azure
    items:
    - name: azure_module
      href: https://galaxy.ansible.com/Azure/azure_modules/
    - name: azure_preview_module
      href: https://galaxy.ansible.com/Azure/azure_preview_modules
- name: Resources
  items:
  - name: Official releases
    href: https://github.com/ansible/ansible/releases
  - name: Tools for using Ansible with Azure
    href: ./ansible-tools.md