- name: Ansible on Azure documentation
  href: ./index.yml
- name: Overview
  items:
  - name: About Ansible on Azure
    href: ./ansible-overview.md
- name: Quickstarts
  expanded: true
  items:
    - name: Install Ansible on a Linux VM
      href: /azure/virtual-machines/linux/ansible-install-configure
      maintainContext: true
    - name: Create a Linux VM
      href: /azure/virtual-machines/linux/ansible-create-vm
      maintainContext: true
    - name: Manage a Linux VM
      href: /azure/virtual-machines/linux/ansible-manage-linux-vm
      maintainContext: true
    - name: Run a playbook in Cloud Shell
      href: ./ansible-run-playbook-in-cloudshell.md
- name: Tutorials 
  items:
  - name: AKS
    items:
    - name: Create and configure AKS clusters
      href: ./ansible-create-configure-aks.md
  - name: App Service
    items:
    - name: Create and configure Azure Web Apps
      href: ./ansible-create-configure-azure-web-apps.md
    - name: Scale Azure Web Apps
      href: ./ansible-scale-azure-web-apps.md
  - name: Application Gateway
    items:
    - name: Create and configure Azure Application Gateway
      href: ./ansible-create-configure-application-gateway.md
  - name: Databases
    items:
    - name: Create and configure Azure DB for MySQL
      href: ./ansible-create-configure-mysql.md
  - name: Dynamic inventory
    items:
    - name: Manage dynamic inventories
      href: ./ansible-manage-azure-dynamic-inventories.md
  - name: Virtual network
    items:
    - name: Create and configure route tables
      href: ./ansible-create-configure-route-table.md
  - name: VMSS
    items:
    - name: Create and configure VMSS
      href: ./ansible-create-configure-vmss.md
    - name: Deploy app to VMSS
      href: ./ansible-deploy-app-vmss.md
    - name: Autoscale VMSS
      href: ./ansible-auto-scale-vmss.md
- name: Reference
  items:
  - name: Playbook roles
    items:
    - name: azure_module
      href: https://galaxy.ansible.com/Azure/azure_modules/
    - name: azure_preview_module
      href: https://galaxy.ansible.com/Azure/azure_preview_modules
  - name: Releases and features
    href: ./ansible-matrix.md  
  - name: Azure Container Instances
    href: https://docs.ansible.com/ansible/latest/azure_rm_containerinstance_module.html
  - name: Azure Functions
    href: https://docs.ansible.com/ansible/latest/azure_rm_functionapp_module.html
  - name: Load balancers
    href: https://docs.ansible.com/ansible/latest/azure_rm_loadbalancer_module.html
  - name: Virtual machines
    href: https://docs.ansible.com/ansible/latest/azure_rm_virtualmachine_module.html
  - name: All modules for Azure
    href: https://docs.ansible.com/ansible/latest/list_of_cloud_modules.html#azure
- name: Tools
  items:
  - name: Visual Studio Code extension for Ansible
    href: https://marketplace.visualstudio.com/items?itemName=vscoss.vscode-ansible
