- name: Ansible on Azure
  href: ./index.yml
- name: Overview
  items:
  - name: About Ansible on Azure
    href: ansible-overview.md
- name: Quickstarts
  expanded: true
  items:
    - name: Install and configure Ansible
      href: /azure/virtual-machines/linux/ansible-install-configure
      maintainContext: true
    - name: Create a Linux VM
      href: /azure/virtual-machines/linux/ansible-create-vm
      maintainContext: true
- name: Tutorials 
- name: Samples
- name: Reference 
  items:
  - name: Ansible modules for Azure
    href: http://docs.ansible.com/ansible/latest/list_of_cloud_modules.html#azure
  - name: Ansible reference
    href: http://docs.ansible.com/ansible/latest/dev_guide/index.html
- name: Resources
  items:
  - name: Tools
    href: ./ansible-tools.md