### YamlMime:Landing

title: Microsoft Entra roles documentation
summary: Microsoft Entra role-based access control manages access to Microsoft Entra resources. Create custom roles, assign roles that use administrative units to restrict scope of control, assign application access to groups or users, manage eligibility with Privileged Identity Management (PIM), or delegate permissions to distribute identity management tasks. 


metadata:
  title: Microsoft Entra roles documentation
  description: Learn how to use Microsoft Entra roles to manage access in your organization.
  services: active-directory
  ms.service: active-directory
  ms.subservice: roles
  manager: amycolannino
  ms.topic: landing-page
  ms.date: 12/17/2021
  author: rolyon
  ms.author: rolyon


# linkListType: architecture | concept | deploy | download | get-started | how-to-guide | learn | overview | quickstart | reference | tutorial | video | whats-new

landingContent:
  # Card
  - title: About Microsoft Entra roles
    linkLists:
      - linkListType: overview
        links:
          - text: What is Microsoft Entra RBAC?
            url: custom-overview.md
      - linkListType: concept
        links:
          - text: Understand Microsoft Entra roles
            url: concept-understand-roles.md
          - text: Understand administrative units
            url: administrative-units.md
          - text: Use groups to manage role assignments
            url: groups-concept.md

  # Card
  - title: Choose roles
    linkLists:
      - linkListType: how-to-guide
        links:
          - text: List role definitions
            url: role-definitions-list.md
      - linkListType: reference
        links:
          - text: Built-in roles
            url: permissions-reference.md
          - text: Least privileged roles by task
            url: delegate-by-task.md

  # Card
  - title: List role assignments
    linkLists:
      - linkListType: how-to-guide
        links:
          - text: List role assignments
            url: view-assignments.md

  # Card
  - title: Assign roles
    linkLists:
      - linkListType: how-to-guide
        links:
          - text: Assign roles to users
            url: manage-roles-portal.md
          - text: Assign roles at different scopes
            url: assign-roles-different-scopes.md

  # Card
  - title: Assign roles to groups
    linkLists:
      - linkListType: how-to-guide
        links:
          - text: Create a role-assignable group
            url: groups-create-eligible.md
          - text: Assign roles to groups
            url: groups-assign-role.md

  # Card
  - title: Create custom roles
    linkLists:
      - linkListType: how-to-guide
        links:
          - text: Create a custom role
            url: custom-create.md
          - text: Create custom roles for enterprise apps
            url: custom-enterprise-apps.md

  # Card
  - title: Manage scope with administrative units
    linkLists:
      - linkListType: how-to-guide
        links:
          - text: Create administrative units
            url: admin-units-manage.md
          - text: Add members
            url: admin-units-members-add.md
          - text: Assign roles with scope
            url: admin-units-assign-roles.md
