- name: Azure AD roles documentation
  href: index.yml
- name: Overview
  items:
  - name: Azure AD roles
    href: custom-overview.md
- name: Quickstarts
  items:
  - name: Create unlimited app registrations
    href: quickstart-app-registration-limits.md
- name: Tutorials
  items:
  - name: Create a dynamic group    
    href: ../enterprise-users/users-revoke-access.md?context=azure%2factive-directory%2froles%2fcontext%2fugr-context
- name: Concepts
  expanded: true
  items:
  - name: Delegate Azure AD admin roles
    href: concept-delegation.md
  - name: Compare default user permissions    
    href: ../fundamentals/users-default-permissions.md?context=azure%2factive-directory%2froles%2fcontext%2fugr-context
  - name: Compare Azure and Azure AD roles    
    href: ../../role-based-access-control/rbac-and-directory-admin-roles.md?context=azure%2factive-directory%2froles%2fcontext%2fugr-context
  - name: Understand administrative units in Azure AD
    href: administrative-units.md
- name: How-to guides
  expanded: true
  items:
  - name: Users and roles
    items:
    - name: Assign users to admin roles
      href: ../fundamentals/active-directory-users-assign-role-azure-portal.md?context=azure%2factive-directory%2froles%2fcontext%2fugr-context
    - name: Revoke a user's access
      href: ../enterprise-users/users-revoke-access.md?context=azure%2factive-directory%2froles%2fcontext%2fugr-context
    - name: Assign role to guest user    
      href: ../b2b/add-guest-to-role.md?context=azure/active-directory/roles/context/ugr-context
    - name: Restrict guest user access
      href: ../enterprise-users/users-restrict-guest-permissions.md?context=azure%2factive-directory%2froles%2fcontext%2fugr-context
    - name: Dynamic groups and guests   
      href: ../b2b/use-dynamic-groups.md?context=azure/active-directory/roles/context/ugr-context
  - name: Roles and permissions
    expanded: true
    items: 
    - name: Roles and permissions
      href: permissions-reference.md
    - name: View and assign roles   
      href: manage-roles-portal.md
    - name: My Staff delegation
      href: my-staff-configure.md
  - name: Custom roles
    expanded: true
    items: 
    - name: Custom roles overview        
      href: custom-overview.md
    - name: Create a custom role
      href: custom-create.md
    - name: View custom role assignments
      href: custom-view-assignments.md
    - name: Assign custom roles in Azure portal
      href: ../fundamentals/active-directory-users-assign-role-azure-portal.md?context=azure%2factive-directory%2froles%2fcontext%2fugr-context
    - name: Assign custom roles in PowerShell
      href: custom-assign-powershell.md
    - name: Assign custom roles for enterprise apps
      href: custom-enterprise-apps.md
    - name: Custom role permissions
      items:
      - name: App registration permissions
        href: custom-available-permissions.md
      - name: Enterprise app permissions
        href: custom-enterprise-app-permissions.md
      - name: App consent permissions
        href: custom-consent-permissions.md
    - name: Delegate app admin role
      href: delegate-app-roles.md
  - name: Assign roles to groups
    items:
    - name: Group-based role assignment preview
      href: groups-concept.md
    - name: Create a role-assignable group
      href: groups-create-eligible.md
    - name: Assign roles to a group
      href: groups-assign-role.md
    - name: Remove role assignments from a group
      href: groups-remove-assignment.md
    - name: View a group's role assignments
      href: groups-view-assignments.md
    - name: Make a group eligible for a role in PIM
      href: groups-pim-eligible.md
    - name: FAQ and troubleshooting
      href: groups-faq-troubleshooting.md
  - name: Secure your roles    
    items:   
    - name: Role security planning    
      href: security-planning.md  
    - name: Create emergency accounts    
      href: security-emergency-access.md
  - name: Administrative units     
    items:
    - name: Administrative units overview  
      href: administrative-units.md
    - name: Add and manage
      href: admin-units-manage.md
    - name: Add and manage users
      href: admin-units-add-manage-users.md
    - name: Add and manage groups
      href: admin-units-add-manage-groups.md
    - name: Assign a role with scope
      href: admin-units-assign-roles.md
    - name: FAQ and troubleshooting
      href: admin-units-faq-troubleshoot.md
  - name: Troubleshoot
    items:
    - name: Get support for Azure AD    
      href: ../fundamentals/active-directory-troubleshooting-support-howto.md?context=azure%2factive-directory%2froles%2fcontext%2fugr-context
- name: Reference
  items:
  - name: Least-privileged roles by task   
    href: delegate-by-task.md
  - name: Microsoft 365 role documentation
    href: m365-workload-docs.md
  - name: Graph API  
    href: /graph/api/resources/azure-ad-overview?view=graph-rest-1.0
  - name: Azure AD CLI    
    href: /cli/azure/ad
  - name:  Azure AD PowerShell for Graph
    href: /powershell/azure/active-directory/install-adv2?view=azureadps-2.0
  - name: Azure AD service limits
    href: ../enterprise-users/directory-service-limits-restrictions.md?context=azure%2factive-directory%2froles%2fcontext%2fugr-context