### YamlMime:HowTo

metadata:
  title: Configure TLS 1.2 on Windows clients accessing Azure Stack Edge Pro GPU device
  description: Describes how to configure TLS 1.2 on Windows clients accessing Azure Stack Edge Pro GPU device.
  author: alkohli
  ms.custom:
    - ge-structured-content-pilot

  ms.service: databox
  ms.subservice: edge
  ms.topic: how-to
  ms.date: 03/21/2024
  ms.author: alkohli
title: |
  Configure TLS 1.2 on Windows clients accessing Azure Stack Edge Pro device
introduction: |
  [!INCLUDE [applies-to-GPU-and-pro-r-and-mini-r-skus](../../includes/azure-stack-edge-applies-to-gpu-pro-r-mini-r-sku.md)]

  If you are using a Windows client to access your Azure Stack Edge Pro device, you are required to configure TLS 1.2 on your client. This article provides resources and guidelines to configure TLS 1.2 on your Windows client. 

  The guidelines provided here are based on testing performed on a client running Windows Server 2016.
prerequisites:
  summary: |
    Before you begin, make sure that you have access to a Windows Server client that can connect to your Azure Stack Edge device. The client should be running Windows Server 2016 or later.
procedureSection:
  - title: |
      Configure TLS 1.2 for current PowerShell session
    summary: |
      Use the following steps to configure TLS 1.2 on your client.
    steps:
      - |
        Run PowerShell as administrator.
      - |  
        To set TLS 1.2 for the current PowerShell session, type:
          
          ```azurepowershell
          [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
          ```
  - title: |
      Configure TLS 1.2 on client
    summary: |
      To set system-wide TLS 1.2 for your environment, follow these steps:
    steps:
      - |
        To enable TLS 1.2 on the clients, use the guidelines in these documents:

          - [General- how to enable TLS 1.2](/windows-server/security/tls/tls-registry-settings#tls-12) 
          - [How to enable TLS 1.2 on clients](/configmgr/core/plan-design/security/enable-tls-1-2-client)
          - [How to enable TLS 1.2 on the site servers and remote site systems](/configmgr/core/plan-design/security/enable-tls-1-2-server)  
          - [Protocols in TLS/SSL (Schannel SSP)](/windows-server/security/tls/manage-tls#configuring-tls-ecc-curve-order)
      - |  
        Configure [Cipher Suites](/windows-server/security/tls/tls-registry-settings#tls-12).
          - Specifically [Configuring TLS Cipher Suite Order](/windows-server/security/tls/manage-tls#configuring-tls-cipher-suite-order)
          - Make sure that you list your current cipher suites and prepend any missing from the following list:

            * TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
            * TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
            * TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384
            * TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384

          You can also add these cipher suites by directly editing the registry settings.
          The variable $HklmSoftwarePath should be defined
          $HklmSoftwarePath = 'HKLM:\SOFTWARE'

          ```azurepowershell
          New-ItemProperty -Path "$HklmSoftwarePath\Policies\Microsoft\Cryptography\Configuration\SSL\00010002" -Name "Functions"  -PropertyType String -Value ("TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384, TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384, TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384,TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384")
          ```
      - |
        Set elliptical curves. Make sure that you list your current elliptical curves and prepend any missing from the following list:
    
          - P-256 
          - P-384

          You can also add these elliptical curves by directly editing the registry settings.
          
          ```azurepowershell
          New-ItemProperty -Path "$HklmSoftwarePath\Policies\Microsoft\Cryptography\Configuration\SSL\00010002" -Name "EccCurves" -PropertyType MultiString -Value @("NistP256", "NistP384")
          ```
      - |    
        [Set min RSA key exchange size to 2048](/windows-server/security/tls/tls-registry-settings#keyexchangealgorithm---client-rsa-key-sizes).

nextStep:
  text: Connect to Azure Resource Manager
  url: ./azure-stack-edge-gpu-connect-resource-manager.md
