### YamlMime:FAQ
metadata:
  title: Azure Web Application Firewall on Application Gateway - Frequently Asked Questions
  description: This article provides answers to frequently asked questions about Azure Web Application Firewall on Application Gateway.
  author: halkazwini
  ms.author: halkazwini
  ms.service: azure-web-application-firewall
  ms.topic: faq
  ms.date: 08/05/2025
title: Frequently asked questions for Azure Web Application Firewall on Application Gateway
summary: This article answers common questions about features and functionality for Azure Web Application Firewall on Azure Application Gateway. 


sections:
  - name: Ignored
    questions:
      - question: |
          What is Azure Web Application Firewall?
        answer: |
          Azure Web Application Firewall is a web application firewall (WAF) that helps protect your web applications from common threats such as SQL injection, cross-site scripting, and other web exploits. You can define a WAF policy that consists of a combination of custom and managed rules to control access to your web applications.
          
          You can apply a WAF policy to web applications hosted on Azure Application Gateway or Azure Front Door.
          
      - question: |
          What features does the WAF product tier support?
        answer: |
          The WAF tier of Application Gateway supports all the features available in the Standard tier.

      - question: |
          How do I monitor the WAF?
        answer: |
          Monitor the WAF through diagnostic logging. For more information, see [Diagnostic logs for Application Gateway](../../application-gateway/application-gateway-diagnostics.md).
          
      - question: |
          Does detection mode block traffic?
        answer: |
          No. Detection mode only logs traffic that triggers a WAF rule.

      - question: |
          Can I customize WAF rules?
        answer: |
          Yes. For more information, see [Customize WAF rules](application-gateway-customize-waf-rules-portal.md).
          
      - question: |
          What rules are currently available for the WAF?
        answer: |
          The WAF currently supports Core Rule Set (CRS) [3.2](application-gateway-crs-rulegroups-rules.md#owasp32), [3.1](application-gateway-crs-rulegroups-rules.md#owasp31), and [3.0](application-gateway-crs-rulegroups-rules.md#owasp30). These rules provide baseline security against most of the top 10 vulnerabilities that Open Web Application Security Project (OWASP) identifies: 
          
          * Protection against SQL injection
          * Protection against cross-site scripting
          * Protection against common web attacks such as command injection, HTTP request smuggling, HTTP response splitting, and remote file inclusion
          * Protection against HTTP protocol violations
          * Protection against HTTP protocol anomalies such as missing `Host`, `User-Agent`, and `Accept` headers
          * Prevention against bots, crawlers, and scanners
          * Detection of common application misconfigurations (for example, Apache and IIS)
          
          For more information, see the [OWASP top 10 vulnerabilities](https://owasp.org/www-project-top-ten/).

          CRS 2.2.9 is no longer supported for new WAF policies. We recommend that you upgrade to the latest CRS version. You can't use CRS 2.2.9 along with CRS 3.2/DRS 2.1 and later versions. 
          
      - question: |
          What content types does the WAF support?
        answer: |
          The Application Gateway WAF supports the following content types for managed rules:
          
          * `application/json`
          * `application/xml`
          * `application/x-www-form-urlencoded`
          * `multipart/form-data`
          
          And for custom rules:
          
          * `application/x-www-form-urlencoded`
          * `application/soap+xml`, `application/xml`, `text/xml`
          * `application/json`
          * `multipart/form-data`
          
      - question: |
          Does the WAF support DDoS protection?
        answer: |
          Yes. You can enable distributed denial-of-service (DDoS) protection on the virtual network where the application gateway is deployed. This setting ensures that the Azure DDoS Protection service also helps protect the application gateway's virtual IP (VIP).
          
      - question: |
          Does the WAF store customer data?
        answer: |
          No, the WAF doesn't store customer data.

      - question: |
          How does the WAF work with WebSocket?
        answer: |
          Azure Application Gateway natively supports WebSocket. WebSocket on the Application Gateway WAF doesn't require any extra configuration to work. However, the WAF doesn't inspect the WebSocket traffic. After the initial handshake between client and server, the data exchange between client and server can be of any format (for example, binary or encrypted). So the WAF can't always parse the data. It just acts as a pass-through proxy for the data.

          For more information, see [Overview of WebSocket support in Application Gateway](../../application-gateway/application-gateway-websocket.md).

additionalContent: |

  ## Related content
  
  - [What is Azure Web Application Firewall?](../overview.md)
  - [What is Azure Front Door?](../../frontdoor/front-door-overview.md)
