### YamlMime:Landing
title: Azure Arc enabled Kubernetes (preview)
summary: Learn how to manage Kubernetes clusters with Azure Arc

metadata:
  title: Azure Arc enabled Kubernetes
  description: Learn about how to manage on-premises machines in Azure
  author: shashankbarsin
  ms.service: azure-arc
  ms.topic: landing-page
  ms.date: 02/08/2021
  ms.author: shasb

landingContent:
  - title: Connect Kubernetes clusters to Azure using Azure Arc
    linkLists: 
      - linkListType: overview
        links:
          - text: What is Azure Arc enabled Kubernetes?
            url: overview.md 
      - linkListType: quickstart
        links:
          - text: Connect cluster
            url: connect-cluster.md
      - linkListType: how-to-guide
        links:  
          - text: Deploy configurations using GitOps
            url: use-gitops-connected-cluster.md
          - text: Deploy Helm charts using GitOps
            url: use-gitops-with-helm.md
          - text: Enforce GitOps using Azure Policy
            url: use-azure-policy.md
          - text: Deploy Azure IoT edge workloads
            url: deploy-azure-iot-edge-workloads.md
 # Card
  - title: Proof of concept
    linkLists:
     - linkListType: sample
       links:
          - text: Jumpstart
            url: https://azurearcjumpstart.io/azure_arc_jumpstart/azure_arc_k8s/
  - title: Reference architecture
    linkLists:
      - linkListType: architecture
        links:
          - text: Manage deployments and configurations for hybrid Kubernetes clusters
            url: /azure/architecture/hybrid/arc-hybrid-kubernetes
