- name: Azure Arc enabled Kubernetes
  href: index.yml
- name: Overview
  items:
  - name: About Arc enabled Kubernetes
    href: overview.md
  - name: Azure Arc Validation Program
    href: validation-program.md
- name: Tutorials
  items:
  - name: Deploy configurations using GitOps
    href: tutorial-use-gitops-connected-cluster.md
- name: Quickstarts
  items:
  - name: Connect a cluster to Azure Arc
    href: quickstart-connect-cluster.md
- name: Concepts
  items:
  - name: Agent architecture
    href: conceptual-agent-architecture.md
  - name: Configurations and GitOps
    href: conceptual-configurations.md
  - name: Frequently Asked Questions
    href: faq.md
- name: How-to guides
  items:
  - name: Connect to Azure Arc
    items:
    - name: Onboarding service principal
      href: create-onboarding-service-principal.md
  - name: Manage
    items:
    - name: Agent upgrades
      href: agent-upgrade.md
  - name: Scenarios
    items:
    - name: Deploy Helm charts using GitOps
      href: use-gitops-with-helm.md
    - name: Enforce GitOps using Azure Policy
      href: use-azure-policy.md
    - name: Monitor using Azure Monitor for containers
      href: ../../azure-monitor/containers/container-insights-enable-arc-enabled-clusters.md?toc=%2fazure%2fazure-arc%2fkubernetes%2ftoc.yml
    - name: Admission control policies using Azure Policy
      href: ../../governance/policy/concepts/policy-for-kubernetes.md?toc=/azure/azure-arc/kubernetes/toc.yml
    - name: Deploy IoT workloads
      href: deploy-azure-iot-edge-workloads.md
  - name: Troubleshooting
    href: Troubleshooting.md
- name: Reference
  items:
  - name: Azure Policy built-ins
    displayName: samples, policies, definitions
    href: policy-reference.md
  - name: Azure PowerShell
    href: /powershell/module/Az.ConnectedKubernetes/
- name: Resources
  items:
    - name: Azure Arc jumpstart
      href: https://azurearcjumpstart.io