- name: Azure Arc enabled Kubernetes
  href: index.yml
- name: Overview
  items:
  - name: About Azure Arc enabled Kubernetes
    href: overview.md
- name: How-to guides
  items:
  - name: Cluster operations
    items:
    - name: Connect a cluster
      href: connect-a-cluster.md
    - name: Use GitOps for connected clusters
      href: use-gitops-in-connected-cluster.md
    - name: Use GitOps with Helm
      href: use-gitops-with-helm.md
    - name: Azure Monitor for containers
      href: deploy-azure-monitor-for-containers.md
    - name: Use Azure Policy
      href: use-azure-policy.md
    - name: Deploy IoT workloads
      href: deploy-azure-iot-edge-workloads.md
    - name: Troubleshooting
      href: Troubleshooting.md
