- name: Azure Arc-enabled Kubernetes
  href: index.yml
- name: Overview
  items:
  - name: About Azure Arc-enabled Kubernetes
    href: overview.md
  - name: Azure Arc validated partners
    href: validation-program.md
- name: Quickstarts
  items:
  - name: Connect a cluster to Azure Arc
    href: quickstart-connect-cluster.md
- name: Tutorials
  items:
  - name: GitOps (Flux v2)
    items:
    - name: Deploy configurations using GitOps (Flux v2)
      href: tutorial-use-gitops-flux2.md
    - name: Implement CI/CD with GitOps (Flux v2)
      href: tutorial-gitops-flux2-ci-cd.md
  - name: GitOps (Flux v1)
    items:
    - name: Deploy configurations using GitOps (Flux v1)
      href: tutorial-use-gitops-connected-cluster.md
    - name: Implement CI/CD with GitOps (Flux v1)
      href: tutorial-gitops-ci-cd.md
- name: Samples
  items:
  - name: Azure Resource Graph queries
    href: ./resource-graph-samples.md
- name: Concepts
  items:
  - name: Agent overview
    href: conceptual-agent-overview.md
  - name: Connectivity modes
    href: conceptual-connectivity-modes.md
  - name: Data exchange between cluster and Azure
    href: conceptual-data-exchange.md
  - name: Identity and access management
    items:
      - name: Azure RBAC
        href: conceptual-azure-rbac.md
  - name: Access cluster from anywhere
    href: conceptual-cluster-connect.md
  - name: Extend Azure capabilities to clusters anywhere
    items:
      - name: Cluster extensions
        href: conceptual-extensions.md
      - name: Custom locations
        href: conceptual-custom-locations.md
  - name: Deploy applications to cluster
    items:
      - name: GitOps (Flux v2)
        items:
        - name: Configurations and GitOps (Flux v2)
          href: conceptual-gitops-flux2.md
        - name: CI/CD workflow using GitOps (Flux v2)
          href: conceptual-gitops-flux2-ci-cd.md
        - name: Inner loop developer experience (Flux v2)
          href: conceptual-inner-loop-gitops.md
      - name: GitOps (Flux v1)
        items:
        - name: Configurations and GitOps (Flux v1)
          href: conceptual-configurations.md
        - name: CI/CD workflow using GitOps (Flux v1)
          href: conceptual-gitops-ci-cd.md        
  - name: Frequently Asked Questions
    href: faq.md

- name: How-to guides
  items:
  - name: Upgrade agents
    href: agent-upgrade.md
  - name: Securely connect to cluster from anywhere
    href: cluster-connect.md
  - name: Use Private Link Scope
    href: private-link.md
  - name: Azure portal Kubernetes resource view
    href: kubernetes-resource-view.md
  - name: Use Azure AD RBAC for authorization checks
    href: azure-rbac.md
  - name: Deploy applications to cluster
    items:
      - name: GitOps (Flux v2)
        items:
        - name: At-scale deployment of Flux v2 configurations using Azure Policy
          href: use-azure-policy-flux-2.md
      - name: GitOps (Flux v1)
        items:
        - name: Deploy Helm charts using GitOps (Flux v1)
          href: use-gitops-with-helm.md
        - name: At-scale deployment of Flux v1 configurations using Azure Policy
          href: use-azure-policy.md
  - name: Manage your cluster
    items:
    - name: Deploy and manage cluster extensions
      href: extensions.md
    - name: Monitor using Azure Monitor for containers
      href: ../../azure-monitor/containers/container-insights-enable-arc-enabled-clusters.md?toc=/azure/azure-arc/kubernetes/toc.json&bc=/azure/azure-arc/kubernetes/breadcrumb/toc.json
    - name: Enforce threat protection using Microsoft Defender for Cloud
      href: ../../defender-for-cloud/defender-for-kubernetes-azure-arc.md?toc=/azure/azure-arc/kubernetes/toc.json&bc=/azure/azure-arc/kubernetes/breadcrumb/toc.json
    - name: In-cluster policy enforcements using Azure Policy
      href: ../../governance/policy/concepts/policy-for-kubernetes.md?toc=/azure/azure-arc/kubernetes/toc.json&bc=/azure/azure-arc/kubernetes/breadcrumb/toc.json#install-azure-policy-extension-for-azure-arc-enabled-kubernetes
    - name: Deploy Azure Arc-enabled Open Service Mesh
      href: tutorial-arc-enabled-open-service-mesh.md
    - name: Access secrets from Azure Key Vault
      href: tutorial-akv-secrets-provider.md
  - name: Deploy Arc-enabled services
    items:
      - name: Create custom locations
        href: custom-locations.md
      - name: Azure Arc-enabled Machine Learning
        href: ../../machine-learning/how-to-attach-kubernetes-anywhere.md?toc=/azure/azure-arc/kubernetes/toc.json&bc=/azure/azure-arc/kubernetes/breadcrumb/toc.json
  - name: Move between regions
    href: move-regions.md
  - name: Troubleshooting
    href: troubleshooting.md
- name: Reference
  items:
  - name: Azure Policy built-ins
    displayName: samples, policies, definitions
    href: policy-reference.md
  - name: Azure CLI
    href: /cli/azure/connectedk8s
  - name: Azure PowerShell
    href: /powershell/module/az.connectedkubernetes#connected-kubernetes
- name: Resources
  items:
    - name: Region availability
      href: https://azure.microsoft.com/global-infrastructure/services/?products=azure-arc
    - name: Plan for deployment
      href: plan-at-scale-deployment.md
    - name: Azure Arc jumpstart
      href: https://azurearcjumpstart.io
